### PR TITLE
minification of html #54

### PR DESCRIPTION
**Pull request by shivamluthra**

### CODE REVIEW

**Comment by butlerx** [comment]
i believe something went wrong with your commit as all thats there is the removal of files which you shouldnt need to remove

**Comment by shivamluthra** [comment]
@butlerx actually i moved all the files to dist folder that's why it is showing that some files have been deleted. else everything is working i have checked

**Comment by shivamluthra** [comment]
@butlerx actually i moved all the files to dist folder that is why it is showing some files have been deleted. Else eveything is working i have checked. please review.

**Comment by butlerx** [comment]
ah right no the dist folder cant be added to the repo you dont need to move them manually you should have it that gulp copies them to dist when ever it is run the original files should remain

**Comment by shivamluthra** [comment]
@butlerx umm.. then what do you say ? should i move them back where they were and again make a PR ?

**Comment by butlerx** [comment]
I think youve misunderstood the issue a little. we use gulp to generate our css and js. so the idea was to minify the html at the same time. so youll want to move them back to there original location and then create a gulp task to duplicate the event.json in the dist folder and minify the html files and place the minified files in the dist folder. Sorry if that wasnt clear before

**Comment by shivamluthra** [comment]
@butlerx yes actually i am new to open-source contributions thats why i couldn't had a sight to that concept. sorry for the inconvenience but still i'll try if i could do it 😊

**Comment by butlerx** [comment]
Go Ahead. :+1:

**Comment by butlerx** [comment]
also if you continue to push to your repo this pr will get updated so you dont have to open a new one

**Comment by shivamluthra** [comment]
@butlerx yaa okay 👍 but actually i am not fully aware about gulp.js presently, so if i could't help, you please see to it.

**Comment by butlerx** [comment]
closed in #61

**Pull request closed without merging**
