### PR TITLE
hash based memory

### PR DESCRIPTION
**Pull request by DeMuu**
added hash based memory to make sure the right item in the accordion
opens even after a page refresh. this also makes specific linking
possible

### CODE REVIEW

**Comment by butlerx** [comment]
just rebase an we can merge

**Comment by butlerx** [comment]
Thanks Really nice feature to have

**Comment by butlerx** [comment]
@DeMuu was testing this before pushing it to prod but i cant seem to get it working

**Comment by DeMuu** [comment]
@butlerx I'm gonna take a look at it when I get home later!

**Comment by butlerx** [comment]
i seem to have it fixed in #50

**Pull request merged**
